spring.application.name=todoservice

spring.datasource.url=jdbc:postgresql://localhost:5433/todoservice
spring.datasource.username=todoservice
spring.datasource.password=todoservice

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
